| Latest update January 10/2013

#event curseofthefirstborn      "#*#A festering darkness saps your strength#*#
#event presentofthefirstborn    "#*#You are dumbstruck by presence of the firstborn#*#
#event hatchet1         "#*#Hatchet hefts#*#
#event hatchet2         "#*#Hatchet lifts#*#
#event hatchet3         "#*#Hatchet levels#*#
#event hatchet3         "#*#Breakneck hoists an arm back, preparing to lob a weighted mallet in your direction.#*#"
#event hatchet3			##*#You feel a small disruption in the air around you#*#"
#event hatchet4         "#*#Hatchet locks#*#
#event hatchet4         "#*#Breakneck locks eyes with you and snorts#*#
#event hatchet6         "#*#You outdistance the reach#*#
#event hatchet6         "#*#By darting between#*#
#event hatchet6         "#*#Hatchet's axe passes#*#
#event hatchet6         "#*#Breakneck's mallet passes harmlessly overhead#*#"
#event doom             "#*#you sense your doom#*#"
#event doom             "#*#Marked for death#*#"
#event doom             "#*#A dire disease creeps through your veins.#*#
#event doom             "#*#Your skin begins to blister#*#
#event doom             "#*#Your movements become stiff.#*#
#event GazeYou          "#*#gaze of deadly power focusing on you#*#"
#event smotherdecay     "#*#You lose your will to fight#*#
#event plagueofmana     "#*#Your blood is tainted with magical essence#*#"
#event queenlocation    "#*#Sendaii begins to look in your direction#*#"
#event Adds             "#*#You hear a strange buzzing around your head, and feel as though something is creeping toward you.#*#"
#event UquaKey          "The #1# Key must unlock the door to the next room."
#event Silence          "#*#The air stops moving around you#*#"
#event hatchet3         "#*#Devlin Draws back his arm and prepares to snap his whip around your neck.#*#"
#event performer        "#*#Recites a line#*#"
#event devlin           "#*#Devlin's whip snaps around#*#"
#event devlin2          "#*#Devlin's whip snaps aroudn your weapon#*#"
#event Randal1          "Ol' Nilipus hailed from Misty Thicket#*#"
#event Randal2          "Where'er he smelled Jumjum he'd pick it#*#"
#event Randal3          "The halflings grew cross#*#"
#event Randal4          "When their profits were lost,#*#"
#event Randal5          "screamin','Where is that brownie? I'll kick it!'#*#"
#event Seth1            "Another night, in eternal darkness.#*#"
#event Seth2            "Time bleeds like a wound that's lost all meaning.#*#"
#event Seth3            "It's a long winter in the swirling chaotic void.#*#"
#event Seth4            "This is my torture,#*#"
#event Seth5            "my pain and suffering!#*#"
#event seth6            "Pinch me, O' Death. . .#*#"
#event Aelfric1         "Touched tenderly.#*#"
#event Aelfric2         "Where will you be?#*#"
#event Aelfric3         "Dreaming with me.#*#"
#event Aelfric4         "Please,#*#"
#event Aelfric5         "everybody, hear the music.#*#"
#event Britton1         "When she and I split ways,#*#"
#event Britton2         "it felt like the end of my days.#*#"
#event Britton3         "Until I suddenly,#*#"
#event Britton4         "suddenly realized#*#"
#event Britton5         "this life was better off alone.#*#"
#event Britton6         "Solitude was the best gift you ever gave me.#*#"
|#event Brekt           "The Master raises his sword, preparing to slash anyone standing nearby.#*#"
#event fero             "You have succumbed to the ferocity of sullon#*#"
#event wrath            "Your knees tremble from the wrath of sullon#*#"
#event banish           "You have fallen victim to Sullon Zek's vengeance.#*#"
#event wrath            "#*#a bolt of energy surges through you#*#"
#event doom             "#*#fire courses#*#"
#event vergalid1        "#*#You feel yourself being exiled.#*#"
#event vergalid2        "#*#You feel something begin to hatch on your skin.#*#"
#event vertigo          "#*#the world is spinning#*#"
#event vertigo2         "#*#you vision blurs#*#"
#event king             "#*#you notice a glint#*#"
#event deepscar         "#*#boulders begin to unlodge above #1#!"
#event irissa           "#*#your view of the world changes#*#"
#event QueenAdd         "#*#You see the queen glare at you#*#"
#event Meldrath11       "#*#And as for you#*#"
#event Meldrath1        "#*#Support Unit turns to face you#*#"
#event Meldrath2        "#*#Physical translation to location of#*#"
#event charge           "#*#An unstable charge courses through you#*#"
#event Sleeper          "#*#You can't concentrate!#*#"
#event Goodnight        "#*#shamalamadingdongdangfucker#*#"
#event Front            "#*#The mighty prismatic dragon prepares a terrible tail strike!#*#"
#event Back             "#*#Kerafyrm tenses for a charge that will overwhelm his foes!#*#"
#event Back             "#*#Kerafyrm exhales a blast of magical prismatic energy!#*#"
#event mindshear        "#*#You get the feeling that someone is watching you#*#"
#event mindblightNW			"#*#The maw in the southeast#*#"
#event mindblightSW			"#*#The maw in the southwest#*#"
#event mindblightSE			"#*#The maw in the northeast#*#"
#event mindblightNE			"#*#The maw in the northwest#*#"
#event Brekt		      	"#*#Lord Brekt prepares to unleash his fury#*#"
#event Brekt				"#*#The rotocopter's propellers spin rapidly#*#"
#Event BeastOne      "#*#Grunkuck looks at #1# with glee!#*#"
#Event BeastTwo      "#*#Grunkuck looks at #1# with strange intent#*#"
#Event BeastThree    "#*#insane with rage at #*#"
#Event Brells		     "#*#envelops your body #*#"
#Event CV2	     "#*#Seething corruption on YOU!#*#"
#Event ROT		 "#*#The Tentacle Terror Mentor points at you, and#*#
#Event ROT		 "#*#The Turbulance Toad glares at you#*#
#event ROT		 "#*#Spinefreezer's eyes all focus upon you, just#*#
#event Sisters "#*#You are surrounded by debilitating energy#*#"
#event ar1 "#*#Aaryonar turns a dreadful gaze upon YOU!#*#"
#event arl2 "#*#Aaryonar turns his gaze away from you#*#"
#event Blob "#*#MOVE FROM BLOB #*#
#event Totem "#*#Seek out the purity stone to remove the filth that surrounds you #*#"
#event Window "#*#Jump from this tower as the ultimate sacrifice to Sholoth#*#"
#event cekenar "#*#You are charged with a bolt of lightning#*#"
#event danela 	"#*#A Ry`Gorr miner throws a barrel of dynamite at ${Me}#*#"
#event chapterhouse "Your bones are burning#*#"

Sub Event_chapterhouse
  /bc I NEED to RUN AWAY!
  /target clear
  /echo running to pool
  /play ChapterPool smart
  /delay 1s ${Me.Moving}
  :MoveChaptSafeSpot
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :MoveChaptSafeSpot
  :WaitChaptDot
   /delay 1s !${Me.Buff[Scorching Bones].ID}
  /if (${Me.Buff[Scorching Bones].ID}) /goto :WaitChaptDot
  /echo Running back to camp
  /play ChapterReturn smart
  /delay 1s ${Me.Moving}
  :BackToChaptCamp
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :BackToChaptCamp
/return

Sub Event_cekenar
/moveto loc 1216 -1093
/delay 7s !${Me.Buff[Lightning Charge].ID}
/call leash
/return

sub Event_window
/tell ${EventsMaster} i need to jump out the window
/return

sub Event_Totem
/tell ${EventsMaster} i need to hug totem
/return

Sub Event_Blob
/tell ${EventsMaster} i need to move away from the blob
/return


sub Event_ar1
/if (!${Defined[Safe]}) /declare Safe bool outer false 
/target Aaryonar
/delay 1s
/face away
:safecheck
/doevents arl2
/if (${MeleeList.Find[${Me.Class.Name}]}) /delay 8s
/return

sub event_arl2
/varset Safe TRUE
/return

Sub Event_Sisters
/bc I GOT EMOTE TO MOVE!
/return

Sub Event_ROT
/bc I GOT EMOTE TO RUN!
/moveto loc -988.70 103
/delay 5s
/return

Sub Event_CV2
/bc I GOT EMOTE To RUN!
/moveto loc -750.09 1182.75
/delay 2s
/moveto loc -974 1173
/tell ${EventsMaster} I NEED TO RUN!
/delay 10s
/return

Sub Event_Brells
  /bc I GOT THE EMOTE TO RUN FROM RAID!
/return

Sub Event_BeastOne(line,person)
  /if (${person.Equal[${Me}]}) {
  	/bc DD about to hit me!
  	/bc DD about to hit me!
  	/bc DD about to hit me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_BeastTwo(line,person)
  /if (${person.Equal[${Me}]}) {
  	/bc  Silence about to hit me!
  	/bc  Silence about to hit me!
  	/bc  Silence about to hit me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_BeastThree(line,person)
/if (${line.Find[${Me}]}) {
  	/bc  mate about to ae on me!
  	/bc  mate about to ae on me!
  	/bc  mate about to ae on me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_Brekt
/if (!${MeleeList.Find[${Me.Class.Name}]}) /Return
/stick 100 moveback
/delay 6s
/target clear
/return

Sub Event_mindblightNW
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 215 71
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightSW
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 201 -79
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightSE
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 92 82 
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightNE
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 94 -86
/delay 20s !${MoveTo.Moving}
/return

Sub Event_Back
|   /declare MeleeList string local Bard|Ranger|Berserker|Rogue|Warrior|Paladin|ShadowKnight|Beastlord|Monk
   /if (${MeleeList.Find[${Me.Class}]}) /squelch /stick ${StickSetting} behind
   /return

Sub Event_Front
|   /declare MeleeList string local Bard|Ranger|Berserker|Rogue|Warrior|Paladin|ShadowKnight|Beastlord|Monk
   /if (${MeleeList.Find[${Me.Class}]}) /squelch /stick ${StickSetting} front
   /return
   
Sub Event_mindshear
/tell ${EventsMaster} i need to move away from the raid
/return

Sub event_hatchet1
  /i say I NEED TO RUN AWAY
  /squelch /stick pause
  /declare running          int   local
  /declare distanceNow      float local
  /declare distanceBefore   float local
  /declare distanceModifier int   local
  /declare MoveToID         int   local ${Spawn[Hatchet].ID}
  /declare StopDistance     int   local 200
  /declare distanceTimer    timer 15
  /varset  distanceBefore   ${Spawn[${MoveToID}].Distance}
  /varset  distanceModifier 1
  /varset  running 0

  :moveAway
  /squelch /face fast away id ${MoveToID}

  /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
    /keypress forward
    /i say I am far from Hatchet!!!
    /return
  }   
  /if (${distanceTimer}==0) {
    /if (${Me.Sneaking}) {
      /varset distanceModifier 2
    } else {
      /varset distanceModifier 1
    }
    /varset distanceNow ${Spawn[${MoveToID}].Distance}
    /if (${Math.Calc[${distanceBefore}-${distanceNow}]}<${Math.Calc[10/${distanceModifier}]}) {
      /keypress forward
      /if (${Math.Rand[99]}>50) {
        /keypress strafe_right hold
      } else {
        /keypress strafe_left hold
      }
      /delay 1s
      /keypress strafe_right
      /keypress strafe_left
      /keypress forward hold
    }
    /varset distanceBefore ${Spawn[${MoveToID}].Distance}
    /varset distanceTimer 15
  }
  /if (${running}==0) {
    /keypress forward
    /if (${Spawn[${MoveToID}].Distance}<=${StopDistance}) {
      /varset running 1
      /keypress forward hold
    }
  } else {
    /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
      /varset running 0
      /keypress forward
    }
    /goto :moveAway
  }
  /return

Sub event_hatchet2
  /i say I NEED TO RUN BETWEEN HIS LEGS
  /declare running          int local
  /declare distanceNow      float local
  /declare distanceBefore   float local
  /declare distanceModifier int   local
  /declare MoveToID         int   local ${Spawn[Hatchet].ID}
  /declare StopDistance     int   local 6
  /declare distanceTimer    timer 15
  /varset  distanceBefore   ${Spawn[${MoveToID}].Distance}
  /varset  distanceModifier 1
  /varset  running 0

  :moveToSpawn
  /squelch /face fast nolook id ${MoveToID}
  /if (${Spawn[${MoveToID}].Distance}<${StopDistance}) {
    /keypress forward
    /i say I am at Hatchet!!!
    /return
  }
  /if (${distanceTimer}==0) {
    /if (${Me.Sneaking}) {
      /varset distanceModifier 2
    } else {
      /varset distanceModifier 1
    }
    /varset distanceNow ${Spawn[${MoveToID}].Distance}
    /if (${Math.Calc[${distanceBefore}-${distanceNow}]}<${Math.Calc[10/${distanceModifier}]}) {
      /keypress forward
      /if (${Math.Rand[99]}>50) {
        /keypress strafe_right hold
      } else {
        /keypress strafe_left hold
      }
    /delay 1s
    /keypress strafe_right
    /keypress strafe_left
    /keypress forward hold
    }
  /varset distanceBefore ${Spawn[${MoveToID}].Distance}
  /varset distanceTimer 15
  }
  /if (${running}==0) {
    /keypress forward
    /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
      /varset running 1
      /keypress forward hold
    }
  } else {
    /if (${Spawn[${MoveToID}].Distance}<${StopDistance}) {
      /varset running 0
      /keypress forward
    }
  }
  /goto :moveToSpawn
  /return

Sub event_hatchet3
  /tell ${EventsMaster} I NEED TO DUCK
  /if (!${Me.Ducking}) /keypress duck
  /delay 15s
  /return

Sub event_hatchet4
  /tell ${EventsMaster} I NEED TO KITE HATCHET!!
  /return

Sub event_hatchet6
  /tell ${EventsMaster} DANGER IS GONE!
  /if (${Me.Ducking}) /keypress duck
  /return

Sub event_doom
  /tell ${EventsMaster} I got DT!
  /if (!${FindItem[distillate of immunization VI].Timer} && ${Me.Buff[mark of death].ID}) /call cast "distillate of immunization VI" item 1s
  /if (!${FindItem[distillate of celestial healing xiii].Timer}) /call cast "distillate of celestial healing xiii" item 1s
  /return

Sub event_GazeYou
  /if (!${Spawn[npc "overlord mata muram"].ID}) /return
  /declare OldItem string local

  /popup CLICK ON THE MASK!
  /tell ${EventsMaster} I GOT MASK EMOTE!

  /if ( ${Me.Casting.ID} ) /stopcast
  /if (${Me.Inventory[face].Name.NotEqual[Mirrored Mask]}) {
    /varset OldItem ${Me.Inventory[face].Name}
    /exchange "Mirrored Mask" face
    /delay 1
    /call Cast "mirrored mask" item 3s
    /exchange "${OldItem}" face
  } else {
    /call Cast "${Me.Inventory[face].Name}" item 3s
  }
  /return

Sub Event_smotherdecay
  /tell ${EventsMaster} I'm snared/slow i need to click on the blue crystal
  /return

Sub Event_curseofthefirstborn
  /tell ${EventsMaster} My stats are deduced. i need to click on the yellow crystal.
  /return

Sub Event_presentofthefirstborn
  /tell ${EventsMaster} I'm silenced. I need to click on the red crystal
  /return

Sub Event_plagueofmana
  /tell ${EventsMaster} I have the 3k dot on me. I need to click on the green crystal.
  /return

Sub Event_Silence
  /tell ${EventsMaster} i'm silenced!
  /return

Sub Event_Adds
  /tell ${EventsMaster} The adds are going to spawn right on top of me!
  /return

Sub Event_UquaKey(string line,string key)
  /tell ${EventsMaster} ${key}
  /return

Sub Event_queenlocation
  /tell ${EventsMaster} Queen is heading right for me
  /return

Sub Event_performer
  /tell ${EventsMaster} I need to recite A line!
  /return

Sub Event_devlin
  /tell ${EventsMaster} i need to remove A piece of gear!
  /return

Sub Event_devlin2
  /tell ${EventsMaster} i need to remove my weapon!
  /itemnotify mainhand leftmouseup
  /delay 9s
  /autoinventory
  /return

Sub SpeakLine
  :speakloop
  /attack off
  /if (${Spawn[${Param0}].Distance}>50) {
    /popup Move Closer To ${Param0}
    /delay 1s
    /goto :speakloop
  } else {
    /target ${Param0}
    /delay 1s ${Target.CleanName.Equal[${Param0}]}
    /delay ${Math.Rand[15]}
    /say ${Param1}
  }
  /squelch /target clear
  /return

Sub Event_Randal1
  /call SpeakLine "Randal Reedsea" "Where'er he smelled Jumjum he'd pick it."
  /return

Sub Event_Randal2
  /call SpeakLine "Randal Reedsea" "The halflings grew cross"
  /return

Sub Event_Randal3
  /call SpeakLine "Randal Reedsea" "When their profits were lost,"
  /return

Sub Event_Randal4
  /call SpeakLine "Randal Reedsea" "screamin', 'Where is that brownie? I'll kick it!'"
  /return

Sub Event_Randal5
  /call SpeakLine "Randal Reedsea" "Ol' Nilipus hailed from Misty Thicket."
  /return

Sub Event_Seth1
  /call SpeakLine "Seth Kimble" "Time bleeds like a wound that's lost all meaning."
  /return

Sub Event_Seth2
  /call SpeakLine "Seth Kimble" "It's a long winter in the swirling chaotic void."
  /return

Sub Event_Seth3
  /call SpeakLine "Seth Kimble" "This is my torture,"
  /return

Sub Event_Seth4
  /call SpeakLine "Seth Kimble" "my pain and suffering!"
  /return

Sub Event_Seth5
  /call SpeakLine "Seth Kimble" "Pinch me, O'Death. . ."
  /return

Sub Event_Seth6
  /call SpeakLine "Seth Kimble" "Another night, in eternal darkness."
  /return

Sub Event_Aelfric1
  /call SpeakLine "Aelfric the Flautist" "Where will you be?"
  /return

Sub Event_Aelfric2
  /call SpeakLine "Aelfric the Flautist" "Dreaming with me."
  /return

Sub Event_Aelfric3
  /call SpeakLine "Aelfric the Flautist" "Please,"
  /return

Sub Event_Aelfric4
  /call SpeakLine "Aelfric the Flautist" "everybody, hear the music."
  /return

Sub Event_Aelfric5
  /call SpeakLine "Aelfric the Flautist" "Touched tenderly."
  /return

Sub Event_Britton1
  /call SpeakLine "Britton Harmony" "it felt like the end of my days."
  /return

Sub Event_Britton2
  /call SpeakLine "Britton Harmony" "Until I suddenly,"
  /return

Sub Event_Britton3
  /call SpeakLine "Britton Harmony" "Suddenly realized"
  /return

Sub Event_Britton4
  /call SpeakLine "Britton Harmony" "this life was better off alone."
  /return

Sub Event_Britton5
  /call SpeakLine "Britton Harmony" "Solitude was the best gift you ever gave me."
  /return

Sub Event_Britton6
  /call SpeakLine "Britton Harmony" "When she and I split ways,"
  /return

Sub Event_Mayong
  /tell ${EventsMaster} i need to get away from mayong!
  /return

Sub Event_fero
  /tell ${EventsMaster} i have fero i need to get away from the raid!
  /return

Sub Event_wrath
  /tell ${EventsMaster} i have wrath. i need to get away from the raid!
  /return

Sub Event_vergalid1
  /tell ${EventsMaster} i'm about to be banished!
  /if (${Me.Buff[Dooming Exile].ID} && ${Me.AltAbilityReady[radiant cure]}) /call cast "radiant cure" alt 3s
  /if (${Me.Buff[Dooming Exile].ID}) {
    /target npc an infused crystal
    /stick 5
    /attack on
    /delay 6s !${Me.Buff[Dooming Exile].ID}
  }
  /return

Sub Event_vergalid2
  /if (${Me.Buff[Breed of Corruption].ID} && ${Me.AltAbilityReady[radiant cure]}) /call cast "radiant cure" alt 3s
  /if (${Me.Buff[Breed of Corruption].ID}) {
    /target npc an infused crystal
    /stick 5
    /attack on
    /delay 6s !${Me.Buff[Breed of Corruption].ID}
  }
  /return

Sub Event_banish
  /tell ${EventsMaster} i got banished!
  /return

Sub Event_vertigo
  /tell ${EventsMaster} i got the drunk dot on me
  /return

Sub Event_vertigo2
  /tell ${EventsMaster} i just got warped
  /stick off
  /return

Sub Event_king
  /i say I'm getting the archer emote
  /return

Sub event_deepscar(line,person)
  /if ( ${person.Equal[${Me}]})  /tell ${EventsMaster} I'm getting the boulders emote!
  /return

Sub Event_irissa
  /tell ${EventsMaster} I GOT IRISSA's DEBUFF!
  /return

Sub Event_QueenAE
  /bc Getting away from Queen
  /if (${Spawn[Queen Malarian].Distance}>30) {
    /bc Far enough from Queen
    /return
  }
  /target clear
  /play QueenAE smart
  /return

Sub Event_QueenAdd
  /bc I NEED to RUN AWAY!
  /target clear
  /play QueenAdd smart
  /delay 1s ${Me.Moving}
  :MoveToQueenSafeSpot
  /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :MoveToQueenSafeSpot
  :CheckQueenAE
  /delay 1s ${Me.Buff[Wave of Infestation].ID}
  /if (!${Me.Buff[Wave of Infestation].ID}) /goto :CheckQueenAE
  :CureQueenAE
  /delay 1s !${Me.Buff[Wave of Infestation].ID}
  /if (${Me.Buff[Wave of Infestation].ID}) /goto :CureQueenAE
  /play RunToQueenCamp
  /delay 1s ${Me.Moving}
  :BackToQueenCamp
  /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :BackToQueenCamp
  /return

Sub Event_Meldrath11
  /tell ${EventsMaster} I GOT MELDRATH AE
  /return

Sub Event_Meldrath2
  /tell ${EventsMaster} BOMB COMING to Me
  /return

Sub Event_charge
  /tell ${EventsMaster} I need cure corruption quick
  /return

Sub Event_Sleeper
  /if (!${Defined[SleeperCastTimer]}) {
    /declare SleeperCastTimer int outer ${Macro.RunTime}
    /echo Declaring SleeperCastTimer at 10s
  } else {
    /varset SleeperCastTimer ${Math.Calc[${Macro.RunTime}+10]}
    /echo Reseting SleeperCastTimer at 10s
  }
  /if (!${Defined[SleeperTimer]}) {
  	/declare SleeperTimer timer outer 10s
  } else {
  	/varset SleeperTimer 10s
  }
/return

Sub Event_Goodnight
  /camp desktop
  /end
  /return
